// GENERATED by scripts/build-blocks-catalog.mjs from blocks/index.json. Do not edit by hand.
// Static JSON imports let wrangler bundle every block spec into the Pages Functions worker.
// This module exports data only (no onRequest* handler), so Pages does not route it.

import b0 from '../../blocks/app-specific/api-keys-page-01.json' with { type: 'json' };
import b1 from '../../blocks/app-specific/billing-page-01.json' with { type: 'json' };
import b2 from '../../blocks/app-specific/changelog-page-01.json' with { type: 'json' };
import b3 from '../../blocks/app-specific/onboarding-tour-01.json' with { type: 'json' };
import b4 from '../../blocks/app-specific/profile-page-01.json' with { type: 'json' };
import b5 from '../../blocks/app-specific/settings-page-01.json' with { type: 'json' };
import b6 from '../../blocks/auth/auth-page-01.json' with { type: 'json' };
import b7 from '../../blocks/auth/forgot-password-01.json' with { type: 'json' };
import b8 from '../../blocks/auth/forgot-password-check-email-01.json' with { type: 'json' };
import b9 from '../../blocks/auth/forgot-password-form-01.json' with { type: 'json' };
import b10 from '../../blocks/auth/forgot-password-new-password-01.json' with { type: 'json' };
import b11 from '../../blocks/auth/forgot-password-success-01.json' with { type: 'json' };
import b12 from '../../blocks/auth/login-form-01.json' with { type: 'json' };
import b13 from '../../blocks/auth/login-page-card-01.json' with { type: 'json' };
import b14 from '../../blocks/auth/login-page-card-02.json' with { type: 'json' };
import b15 from '../../blocks/auth/login-page-illustration-01.json' with { type: 'json' };
import b16 from '../../blocks/auth/login-page-minimal-01.json' with { type: 'json' };
import b17 from '../../blocks/auth/login-page-nav-01.json' with { type: 'json' };
import b18 from '../../blocks/auth/login-page-simple-01.json' with { type: 'json' };
import b19 from '../../blocks/auth/login-page-social-01.json' with { type: 'json' };
import b20 from '../../blocks/auth/login-page-social-leading-01.json' with { type: 'json' };
import b21 from '../../blocks/auth/login-split-carousel-01.json' with { type: 'json' };
import b22 from '../../blocks/auth/login-split-geometric-01.json' with { type: 'json' };
import b23 from '../../blocks/auth/login-split-image-01.json' with { type: 'json' };
import b24 from '../../blocks/auth/login-split-image-quote-01.json' with { type: 'json' };
import b25 from '../../blocks/auth/login-split-mockup-01.json' with { type: 'json' };
import b26 from '../../blocks/auth/login-split-mockup-quote-01.json' with { type: 'json' };
import b27 from '../../blocks/auth/login-split-quote-01.json' with { type: 'json' };
import b28 from '../../blocks/auth/register-form-01.json' with { type: 'json' };
import b29 from '../../blocks/auth/reset-password-01.json' with { type: 'json' };
import b30 from '../../blocks/auth/signup-card-01.json' with { type: 'json' };
import b31 from '../../blocks/auth/signup-card-02.json' with { type: 'json' };
import b32 from '../../blocks/auth/signup-nav-01.json' with { type: 'json' };
import b33 from '../../blocks/auth/signup-progress-01.json' with { type: 'json' };
import b34 from '../../blocks/auth/signup-progress-02.json' with { type: 'json' };
import b35 from '../../blocks/auth/signup-progress-03.json' with { type: 'json' };
import b36 from '../../blocks/auth/signup-sidebar-progress-01.json' with { type: 'json' };
import b37 from '../../blocks/auth/signup-sidebar-progress-02.json' with { type: 'json' };
import b38 from '../../blocks/auth/signup-sidebar-progress-03.json' with { type: 'json' };
import b39 from '../../blocks/auth/signup-simple-01.json' with { type: 'json' };
import b40 from '../../blocks/auth/signup-social-01.json' with { type: 'json' };
import b41 from '../../blocks/auth/signup-social-leading-01.json' with { type: 'json' };
import b42 from '../../blocks/auth/signup-split-app-mockup-01.json' with { type: 'json' };
import b43 from '../../blocks/auth/signup-split-arrow-01.json' with { type: 'json' };
import b44 from '../../blocks/auth/signup-split-carousel-01.json' with { type: 'json' };
import b45 from '../../blocks/auth/signup-split-gradient-01.json' with { type: 'json' };
import b46 from '../../blocks/auth/signup-split-image-bg-01.json' with { type: 'json' };
import b47 from '../../blocks/auth/signup-split-mockup-01.json' with { type: 'json' };
import b48 from '../../blocks/auth/signup-split-mockup-quote-01.json' with { type: 'json' };
import b49 from '../../blocks/auth/signup-split-quote-carousel-01.json' with { type: 'json' };
import b50 from '../../blocks/auth/signup-split-quote-image-01.json' with { type: 'json' };
import b51 from '../../blocks/auth/signup-split-quote-image-02.json' with { type: 'json' };
import b52 from '../../blocks/auth/social-login-01.json' with { type: 'json' };
import b53 from '../../blocks/auth/two-factor-01.json' with { type: 'json' };
import b54 from '../../blocks/banners/banner-bottom-sticky-01.json' with { type: 'json' };
import b55 from '../../blocks/banners/banner-inline-01.json' with { type: 'json' };
import b56 from '../../blocks/banners/banner-top-01.json' with { type: 'json' };
import b57 from '../../blocks/blog/blog-featured-01.json' with { type: 'json' };
import b58 from '../../blocks/blog/blog-grid-01.json' with { type: 'json' };
import b59 from '../../blocks/blog/blog-list-01.json' with { type: 'json' };
import b60 from '../../blocks/blog/blog-newsletter-01.json' with { type: 'json' };
import b61 from '../../blocks/blog/blog-post-header-01.json' with { type: 'json' };
import b62 from '../../blocks/blog/blog-sidebar-01.json' with { type: 'json' };
import b63 from '../../blocks/comparison/before-after-01.json' with { type: 'json' };
import b64 from '../../blocks/comparison/comparison-table-01.json' with { type: 'json' };
import b65 from '../../blocks/comparison/vs-layout-01.json' with { type: 'json' };
import b66 from '../../blocks/contact/contact-form-simple-01.json' with { type: 'json' };
import b67 from '../../blocks/contact/contact-info-01.json' with { type: 'json' };
import b68 from '../../blocks/contact/contact-offices-01.json' with { type: 'json' };
import b69 from '../../blocks/contact/contact-split-01.json' with { type: 'json' };
import b70 from '../../blocks/contact/contact-with-map-01.json' with { type: 'json' };
import b71 from '../../blocks/content/content-numbered-steps-01.json' with { type: 'json' };
import b72 from '../../blocks/content/content-quote-highlight-01.json' with { type: 'json' };
import b73 from '../../blocks/content/content-section-01.json' with { type: 'json' };
import b74 from '../../blocks/content/content-split-01.json' with { type: 'json' };
import b75 from '../../blocks/content/content-video-embed-01.json' with { type: 'json' };
import b76 from '../../blocks/content/content-with-image-01.json' with { type: 'json' };
import b77 from '../../blocks/cta/cta-abstract-images-01.json' with { type: 'json' };
import b78 from '../../blocks/cta/cta-banner-01.json' with { type: 'json' };
import b79 from '../../blocks/cta/cta-card-horizontal-01.json' with { type: 'json' };
import b80 from '../../blocks/cta/cta-card-horizontal-split-01.json' with { type: 'json' };
import b81 from '../../blocks/cta/cta-card-vertical-01.json' with { type: 'json' };
import b82 from '../../blocks/cta/cta-download-01.json' with { type: 'json' };
import b83 from '../../blocks/cta/cta-floating-01.json' with { type: 'json' };
import b84 from '../../blocks/cta/cta-iphone-mockup-01.json' with { type: 'json' };
import b85 from '../../blocks/cta/cta-iphone-mockup-02.json' with { type: 'json' };
import b86 from '../../blocks/cta/cta-iphone-mockup-03.json' with { type: 'json' };
import b87 from '../../blocks/cta/cta-iphone-mockup-04.json' with { type: 'json' };
import b88 from '../../blocks/cta/cta-screen-mockup-01.json' with { type: 'json' };
import b89 from '../../blocks/cta/cta-screen-mockup-02.json' with { type: 'json' };
import b90 from '../../blocks/cta/cta-screen-mockup-03.json' with { type: 'json' };
import b91 from '../../blocks/cta/cta-screen-mockup-04.json' with { type: 'json' };
import b92 from '../../blocks/cta/cta-simple-01.json' with { type: 'json' };
import b93 from '../../blocks/cta/cta-simple-centered-01.json' with { type: 'json' };
import b94 from '../../blocks/cta/cta-simple-left-01.json' with { type: 'json' };
import b95 from '../../blocks/cta/cta-simple-logos-01.json' with { type: 'json' };
import b96 from '../../blocks/cta/cta-simple-logos-02.json' with { type: 'json' };
import b97 from '../../blocks/cta/cta-split-01.json' with { type: 'json' };
import b98 from '../../blocks/cta/cta-split-image-01.json' with { type: 'json' };
import b99 from '../../blocks/cta/cta-split-image-02.json' with { type: 'json' };
import b100 from '../../blocks/cta/cta-split-image-03.json' with { type: 'json' };
import b101 from '../../blocks/cta/cta-split-image-04.json' with { type: 'json' };
import b102 from '../../blocks/cta/cta-split-image-quote-01.json' with { type: 'json' };
import b103 from '../../blocks/cta/cta-split-image-quote-02.json' with { type: 'json' };
import b104 from '../../blocks/cta/cta-split-image-quote-03.json' with { type: 'json' };
import b105 from '../../blocks/cta/cta-split-image-quote-04.json' with { type: 'json' };
import b106 from '../../blocks/cta/cta-with-form-01.json' with { type: 'json' };
import b107 from '../../blocks/dashboard/activity-feed-01.json' with { type: 'json' };
import b108 from '../../blocks/dashboard/chart-panel-01.json' with { type: 'json' };
import b109 from '../../blocks/dashboard/chart-section-01.json' with { type: 'json' };
import b110 from '../../blocks/dashboard/dashboard-header-01.json' with { type: 'json' };
import b111 from '../../blocks/dashboard/data-table-01.json' with { type: 'json' };
import b112 from '../../blocks/dashboard/empty-state-panel-01.json' with { type: 'json' };
import b113 from '../../blocks/dashboard/header-01.json' with { type: 'json' };
import b114 from '../../blocks/dashboard/kanban-board-01.json' with { type: 'json' };
import b115 from '../../blocks/dashboard/notification-panel-01.json' with { type: 'json' };
import b116 from '../../blocks/dashboard/sidebar-layout-01.json' with { type: 'json' };
import b117 from '../../blocks/dashboard/stats-cards-row-01.json' with { type: 'json' };
import b118 from '../../blocks/dashboard/stats-row-01.json' with { type: 'json' };
import b119 from '../../blocks/data-display/empty-state-01.json' with { type: 'json' };
import b120 from '../../blocks/data-display/notification-center-01.json' with { type: 'json' };
import b121 from '../../blocks/data-display/profile-01.json' with { type: 'json' };
import b122 from '../../blocks/ecommerce/category-grid-01.json' with { type: 'json' };
import b123 from '../../blocks/ecommerce/checkout-form-01.json' with { type: 'json' };
import b124 from '../../blocks/ecommerce/order-summary-01.json' with { type: 'json' };
import b125 from '../../blocks/ecommerce/product-card-01.json' with { type: 'json' };
import b126 from '../../blocks/ecommerce/product-carousel-01.json' with { type: 'json' };
import b127 from '../../blocks/ecommerce/product-detail-01.json' with { type: 'json' };
import b128 from '../../blocks/ecommerce/product-grid-01.json' with { type: 'json' };
import b129 from '../../blocks/ecommerce/shopping-cart-01.json' with { type: 'json' };
import b130 from '../../blocks/ecommerce/wishlist-01.json' with { type: 'json' };
import b131 from '../../blocks/error-pages/404-illustration-01.json' with { type: 'json' };
import b132 from '../../blocks/error-pages/404-illustration-02.json' with { type: 'json' };
import b133 from '../../blocks/error-pages/404-illustration-03.json' with { type: 'json' };
import b134 from '../../blocks/error-pages/404-illustration-04.json' with { type: 'json' };
import b135 from '../../blocks/error-pages/404-page-01.json' with { type: 'json' };
import b136 from '../../blocks/error-pages/404-simple-01.json' with { type: 'json' };
import b137 from '../../blocks/error-pages/404-simple-02.json' with { type: 'json' };
import b138 from '../../blocks/error-pages/404-simple-03.json' with { type: 'json' };
import b139 from '../../blocks/error-pages/404-simple-04.json' with { type: 'json' };
import b140 from '../../blocks/error-pages/404-split-image-01.json' with { type: 'json' };
import b141 from '../../blocks/error-pages/404-split-image-02.json' with { type: 'json' };
import b142 from '../../blocks/error-pages/404-split-image-03.json' with { type: 'json' };
import b143 from '../../blocks/error-pages/404-split-image-04.json' with { type: 'json' };
import b144 from '../../blocks/error-pages/500-page-01.json' with { type: 'json' };
import b145 from '../../blocks/error-pages/coming-soon-01.json' with { type: 'json' };
import b146 from '../../blocks/error-pages/maintenance-page-01.json' with { type: 'json' };
import b147 from '../../blocks/event-schedule/event-countdown-01.json' with { type: 'json' };
import b148 from '../../blocks/event-schedule/schedule-tabs-01.json' with { type: 'json' };
import b149 from '../../blocks/event-schedule/speaker-grid-01.json' with { type: 'json' };
import b150 from '../../blocks/faq/faq-accordion-01.json' with { type: 'json' };
import b151 from '../../blocks/faq/faq-grid-01.json' with { type: 'json' };
import b152 from '../../blocks/faq/faq-simple-01.json' with { type: 'json' };
import b153 from '../../blocks/faq/faq-with-sidebar-01.json' with { type: 'json' };
import b154 from '../../blocks/features/feature-alternating-01.json' with { type: 'json' };
import b155 from '../../blocks/features/feature-bento-01.json' with { type: 'json' };
import b156 from '../../blocks/features/feature-centered-01.json' with { type: 'json' };
import b157 from '../../blocks/features/feature-comparison-01.json' with { type: 'json' };
import b158 from '../../blocks/features/feature-grid-01.json' with { type: 'json' };
import b159 from '../../blocks/features/feature-icon-grid-01.json' with { type: 'json' };
import b160 from '../../blocks/features/feature-list-01.json' with { type: 'json' };
import b161 from '../../blocks/features/feature-tabs-01.json' with { type: 'json' };
import b162 from '../../blocks/features/feature-with-code-01.json' with { type: 'json' };
import b163 from '../../blocks/footer/footer-columns-01.json' with { type: 'json' };
import b164 from '../../blocks/footer/footer-mega-01.json' with { type: 'json' };
import b165 from '../../blocks/footer/footer-minimal-01.json' with { type: 'json' };
import b166 from '../../blocks/footer/footer-simple-01.json' with { type: 'json' };
import b167 from '../../blocks/footer/footer-with-cta-01.json' with { type: 'json' };
import b168 from '../../blocks/forms/checkout-01.json' with { type: 'json' };
import b169 from '../../blocks/forms/contact-01.json' with { type: 'json' };
import b170 from '../../blocks/forms/file-upload-01.json' with { type: 'json' };
import b171 from '../../blocks/forms/form-inline-01.json' with { type: 'json' };
import b172 from '../../blocks/forms/form-multi-step-01.json' with { type: 'json' };
import b173 from '../../blocks/forms/form-stacked-01.json' with { type: 'json' };
import b174 from '../../blocks/forms/form-with-sidebar-01.json' with { type: 'json' };
import b175 from '../../blocks/forms/login-01.json' with { type: 'json' };
import b176 from '../../blocks/forms/search-bar-01.json' with { type: 'json' };
import b177 from '../../blocks/forms/settings-01.json' with { type: 'json' };
import b178 from '../../blocks/forms/settings-form-01.json' with { type: 'json' };
import b179 from '../../blocks/forms/signup-01.json' with { type: 'json' };
import b180 from '../../blocks/hero/hero-centered-01.json' with { type: 'json' };
import b181 from '../../blocks/hero/hero-fullscreen-01.json' with { type: 'json' };
import b182 from '../../blocks/hero/hero-minimal-01.json' with { type: 'json' };
import b183 from '../../blocks/hero/hero-split-01.json' with { type: 'json' };
import b184 from '../../blocks/hero/hero-video-background-01.json' with { type: 'json' };
import b185 from '../../blocks/hero/hero-with-app-screenshot-01.json' with { type: 'json' };
import b186 from '../../blocks/hero/hero-with-form-01.json' with { type: 'json' };
import b187 from '../../blocks/hero/hero-with-stats-01.json' with { type: 'json' };
import b188 from '../../blocks/how-it-works/process-alternating-01.json' with { type: 'json' };
import b189 from '../../blocks/how-it-works/steps-horizontal-01.json' with { type: 'json' };
import b190 from '../../blocks/how-it-works/steps-vertical-01.json' with { type: 'json' };
import b191 from '../../blocks/integrations/api-reference-01.json' with { type: 'json' };
import b192 from '../../blocks/integrations/integration-grid-01.json' with { type: 'json' };
import b193 from '../../blocks/integrations/integration-showcase-01.json' with { type: 'json' };
import b194 from '../../blocks/landing/features-grid-01.json' with { type: 'json' };
import b195 from '../../blocks/landing/footer-01.json' with { type: 'json' };
import b196 from '../../blocks/landing/hero-01.json' with { type: 'json' };
import b197 from '../../blocks/landing/pricing-01.json' with { type: 'json' };
import b198 from '../../blocks/landing/testimonials-01.json' with { type: 'json' };
import b199 from '../../blocks/logo-bar/logo-cloud-scrolling-01.json' with { type: 'json' };
import b200 from '../../blocks/logo-bar/logo-cloud-simple-01.json' with { type: 'json' };
import b201 from '../../blocks/logo-bar/logo-cloud-with-heading-01.json' with { type: 'json' };
import b202 from '../../blocks/media/gallery-carousel-01.json' with { type: 'json' };
import b203 from '../../blocks/media/gallery-grid-01.json' with { type: 'json' };
import b204 from '../../blocks/media/media-with-text-01.json' with { type: 'json' };
import b205 from '../../blocks/media/video-section-01.json' with { type: 'json' };
import b206 from '../../blocks/misc/back-to-top-01.json' with { type: 'json' };
import b207 from '../../blocks/misc/divider-01.json' with { type: 'json' };
import b208 from '../../blocks/misc/language-switcher-01.json' with { type: 'json' };
import b209 from '../../blocks/misc/scroll-indicator-01.json' with { type: 'json' };
import b210 from '../../blocks/misc/skip-link-01.json' with { type: 'json' };
import b211 from '../../blocks/misc/social-links-01.json' with { type: 'json' };
import b212 from '../../blocks/misc/table-of-contents-01.json' with { type: 'json' };
import b213 from '../../blocks/misc/theme-toggle-01.json' with { type: 'json' };
import b214 from '../../blocks/mobile/app-shell-01.json' with { type: 'json' };
import b215 from '../../blocks/modals-overlays/command-palette-01.json' with { type: 'json' };
import b216 from '../../blocks/modals-overlays/cookie-consent-01.json' with { type: 'json' };
import b217 from '../../blocks/modals-overlays/drawer-01.json' with { type: 'json' };
import b218 from '../../blocks/modals-overlays/lightbox-01.json' with { type: 'json' };
import b219 from '../../blocks/modals-overlays/modal-confirm-01.json' with { type: 'json' };
import b220 from '../../blocks/modals-overlays/modal-dialog-01.json' with { type: 'json' };
import b221 from '../../blocks/modals-overlays/toast-notification-01.json' with { type: 'json' };
import b222 from '../../blocks/navigation/bottom-nav-01.json' with { type: 'json' };
import b223 from '../../blocks/navigation/breadcrumbs-01.json' with { type: 'json' };
import b224 from '../../blocks/navigation/navbar-mega-menu-01.json' with { type: 'json' };
import b225 from '../../blocks/navigation/navbar-mobile-drawer-01.json' with { type: 'json' };
import b226 from '../../blocks/navigation/navbar-simple-01.json' with { type: 'json' };
import b227 from '../../blocks/navigation/navbar-with-auth-01.json' with { type: 'json' };
import b228 from '../../blocks/navigation/navbar-with-search-01.json' with { type: 'json' };
import b229 from '../../blocks/navigation/pagination-01.json' with { type: 'json' };
import b230 from '../../blocks/navigation/sidebar-nav-01.json' with { type: 'json' };
import b231 from '../../blocks/navigation/tab-nav-01.json' with { type: 'json' };
import b232 from '../../blocks/navigation/topbar-announcement-01.json' with { type: 'json' };
import b233 from '../../blocks/newsletter/newsletter-card-01.json' with { type: 'json' };
import b234 from '../../blocks/newsletter/newsletter-footer-01.json' with { type: 'json' };
import b235 from '../../blocks/newsletter/newsletter-inline-01.json' with { type: 'json' };
import b236 from '../../blocks/newsletter/newsletter-popup-01.json' with { type: 'json' };
import b237 from '../../blocks/portfolio/portfolio-carousel-01.json' with { type: 'json' };
import b238 from '../../blocks/portfolio/portfolio-case-study-01.json' with { type: 'json' };
import b239 from '../../blocks/portfolio/portfolio-grid-01.json' with { type: 'json' };
import b240 from '../../blocks/pricing/pricing-calculator-01.json' with { type: 'json' };
import b241 from '../../blocks/pricing/pricing-comparison-table-01.json' with { type: 'json' };
import b242 from '../../blocks/pricing/pricing-faq-01.json' with { type: 'json' };
import b243 from '../../blocks/pricing/pricing-single-01.json' with { type: 'json' };
import b244 from '../../blocks/pricing/pricing-tiers-01.json' with { type: 'json' };
import b245 from '../../blocks/pricing/pricing-toggle-01.json' with { type: 'json' };
import b246 from '../../blocks/social-proof/case-study-card-01.json' with { type: 'json' };
import b247 from '../../blocks/social-proof/press-mentions-01.json' with { type: 'json' };
import b248 from '../../blocks/social-proof/review-stars-01.json' with { type: 'json' };
import b249 from '../../blocks/social-proof/social-proof-bar-01.json' with { type: 'json' };
import b250 from '../../blocks/social-proof/testimonial-carousel-01.json' with { type: 'json' };
import b251 from '../../blocks/social-proof/testimonial-grid-01.json' with { type: 'json' };
import b252 from '../../blocks/social-proof/testimonial-single-01.json' with { type: 'json' };
import b253 from '../../blocks/social-proof/testimonial-wall-01.json' with { type: 'json' };
import b254 from '../../blocks/stats/stats-counter-01.json' with { type: 'json' };
import b255 from '../../blocks/stats/stats-grid-01.json' with { type: 'json' };
import b256 from '../../blocks/stats/stats-strip-01.json' with { type: 'json' };
import b257 from '../../blocks/stats/stats-with-description-01.json' with { type: 'json' };
import b258 from '../../blocks/team/team-carousel-01.json' with { type: 'json' };
import b259 from '../../blocks/team/team-featured-01.json' with { type: 'json' };
import b260 from '../../blocks/team/team-grid-01.json' with { type: 'json' };
import b261 from '../../blocks/team/team-list-01.json' with { type: 'json' };
import b262 from '../../blocks/timeline/changelog-01.json' with { type: 'json' };
import b263 from '../../blocks/timeline/roadmap-01.json' with { type: 'json' };
import b264 from '../../blocks/timeline/timeline-horizontal-01.json' with { type: 'json' };
import b265 from '../../blocks/timeline/timeline-vertical-01.json' with { type: 'json' };

export const BLOCKS = [
  { id: "api-keys-page-01", category: "app-specific", subcategory: "api-keys-page", description: "API keys page: uses Button, Alert, DataTable", spec: b0 },
  { id: "billing-page-01", category: "app-specific", subcategory: "billing-page", description: "Billing page: uses Button, DataTable", spec: b1 },
  { id: "changelog-page-01", category: "app-specific", subcategory: "changelog-page", description: "Changelog page: Dated release notes with version badges", spec: b2 },
  { id: "onboarding-tour-01", category: "app-specific", subcategory: "onboarding-tour", description: "Onboarding tour: uses Progress, List, Button", spec: b3 },
  { id: "profile-page-01", category: "app-specific", subcategory: "profile-page", description: "Profile page: uses Avatar, Button, StatCard, List", spec: b4 },
  { id: "settings-page-01", category: "app-specific", subcategory: "settings-page", description: "Settings page: uses Sidebar, Select, Switch, Button", spec: b5 },
  { id: "auth-page-01", category: "auth", subcategory: "", description: "Auth page: Split-screen auth: branding panel (left) + login form (right) in 2-column grid", spec: b6 },
  { id: "forgot-password-01", category: "auth", subcategory: "forgot-password", description: "Forgot password: narrow centered; uses Alert, Field, Input, Button, Link", spec: b7 },
  { id: "forgot-password-check-email-01", category: "auth", subcategory: "", description: "Forgot password check email: narrow centered; uses Button, Link", spec: b8 },
  { id: "forgot-password-form-01", category: "auth", subcategory: "", description: "Forgot password form: narrow centered; uses Field, Input, Button, Link", spec: b9 },
  { id: "forgot-password-new-password-01", category: "auth", subcategory: "", description: "Forgot password new password: narrow centered; uses Field, Input, Button, Link", spec: b10 },
  { id: "forgot-password-success-01", category: "auth", subcategory: "", description: "Forgot password success: narrow centered; uses Button, Link", spec: b11 },
  { id: "login-form-01", category: "auth", subcategory: "login-form", description: "Login form: narrow centered; uses Field, Input, Checkbox, Link, Button", spec: b12 },
  { id: "login-page-card-01", category: "auth", subcategory: "", description: "Login page card: narrow centered; uses Field, Input, Checkbox, Link, Button", spec: b13 },
  { id: "login-page-card-02", category: "auth", subcategory: "", description: "Login page card: narrow centered; uses Input, Checkbox, Link, Button", spec: b14 },
  { id: "login-page-illustration-01", category: "auth", subcategory: "", description: "Login page illustration: narrow centered; uses Field, Input, Checkbox, Link, Button", spec: b15 },
  { id: "login-page-minimal-01", category: "auth", subcategory: "", description: "Login page minimal: narrow centered; uses Input, Button, Link", spec: b16 },
  { id: "login-page-nav-01", category: "auth", subcategory: "", description: "Login page nav: uses Link, Field, Input, Checkbox, Button", spec: b17 },
  { id: "login-page-simple-01", category: "auth", subcategory: "", description: "Login page simple: narrow centered; uses Field, Input, Checkbox, Link, Button", spec: b18 },
  { id: "login-page-social-01", category: "auth", subcategory: "", description: "Login page social: narrow centered; uses Input, Button, Link", spec: b19 },
  { id: "login-page-social-leading-01", category: "auth", subcategory: "", description: "Login page social leading: narrow centered; uses Button, Input", spec: b20 },
  { id: "login-split-carousel-01", category: "auth", subcategory: "", description: "Login split carousel: two-column split; uses Field, Input, Checkbox, Link, Button", spec: b21 },
  { id: "login-split-geometric-01", category: "auth", subcategory: "", description: "Login split geometric: two-column split; uses Field, Input, Checkbox, Link, Button", spec: b22 },
  { id: "login-split-image-01", category: "auth", subcategory: "", description: "Login split image: two-column split; uses Field, Input, Checkbox, Link, Button", spec: b23 },
  { id: "login-split-image-quote-01", category: "auth", subcategory: "", description: "Login split image quote: two-column split; uses Field, Input, Checkbox, Link, Button", spec: b24 },
  { id: "login-split-mockup-01", category: "auth", subcategory: "", description: "Login split mockup: two-column split; uses Field, Input, Checkbox, Link, Button", spec: b25 },
  { id: "login-split-mockup-quote-01", category: "auth", subcategory: "", description: "Login split mockup quote: two-column split; uses Field, Input, Checkbox, Link, Button", spec: b26 },
  { id: "login-split-quote-01", category: "auth", subcategory: "", description: "Login split quote: two-column split; uses Avatar, Field, Input, Checkbox, Link", spec: b27 },
  { id: "register-form-01", category: "auth", subcategory: "register-form", description: "Register form: narrow centered; uses Field, Input, Checkbox, Button, Link", spec: b28 },
  { id: "reset-password-01", category: "auth", subcategory: "reset-password", description: "Reset password: narrow centered; uses Field, Input, Progress, Button, Link", spec: b29 },
  { id: "signup-card-01", category: "auth", subcategory: "", description: "Signup card: uses Field, Input, Button, Link", spec: b30 },
  { id: "signup-card-02", category: "auth", subcategory: "", description: "Signup card: uses Field, Input, Button, Link", spec: b31 },
  { id: "signup-nav-01", category: "auth", subcategory: "", description: "Signup nav: uses Link, Field, Input, Button", spec: b32 },
  { id: "signup-progress-01", category: "auth", subcategory: "", description: "Signup progress: narrow centered; uses Field, Input, Button", spec: b33 },
  { id: "signup-progress-02", category: "auth", subcategory: "", description: "Signup progress: narrow centered; uses Field, Input, Button", spec: b34 },
  { id: "signup-progress-03", category: "auth", subcategory: "", description: "Signup progress: narrow centered; uses Field, Input, Button", spec: b35 },
  { id: "signup-sidebar-progress-01", category: "auth", subcategory: "", description: "Signup sidebar progress: uses Avatar, Field, Input, Button", spec: b36 },
  { id: "signup-sidebar-progress-02", category: "auth", subcategory: "", description: "Signup sidebar progress: uses Avatar, Field, Input, Button", spec: b37 },
  { id: "signup-sidebar-progress-03", category: "auth", subcategory: "", description: "Signup sidebar progress: uses Avatar, Field, Input, Button", spec: b38 },
  { id: "signup-simple-01", category: "auth", subcategory: "", description: "Signup simple: narrow centered; uses Field, Input, Button, Link", spec: b39 },
  { id: "signup-social-01", category: "auth", subcategory: "", description: "Signup social: narrow centered; uses Field, Input, Button, Link", spec: b40 },
  { id: "signup-social-leading-01", category: "auth", subcategory: "", description: "Signup social leading: narrow centered; uses Button, Field, Input, Link", spec: b41 },
  { id: "signup-split-app-mockup-01", category: "auth", subcategory: "", description: "Signup split app mockup: two-column split; uses Field, Input, Button, Link, List", spec: b42 },
  { id: "signup-split-arrow-01", category: "auth", subcategory: "", description: "Signup split arrow: two-column split; uses Field, Input, Button, Link, Avatar", spec: b43 },
  { id: "signup-split-carousel-01", category: "auth", subcategory: "", description: "Signup split carousel: two-column split; uses Field, Input, Button, Link", spec: b44 },
  { id: "signup-split-gradient-01", category: "auth", subcategory: "", description: "Signup split gradient: two-column split; uses Field, Input, Button, Link, List", spec: b45 },
  { id: "signup-split-image-bg-01", category: "auth", subcategory: "", description: "Signup split image background: two-column split; uses Avatar, Field, Input, Button, Link", spec: b46 },
  { id: "signup-split-mockup-01", category: "auth", subcategory: "", description: "Signup split mockup: two-column split; uses Field, Input, Button, Link", spec: b47 },
  { id: "signup-split-mockup-quote-01", category: "auth", subcategory: "", description: "Signup split mockup quote: two-column split; uses Field, Input, Button, Link, Avatar", spec: b48 },
  { id: "signup-split-quote-carousel-01", category: "auth", subcategory: "", description: "Signup split quote carousel: two-column split; uses Avatar, Button, Field, Input, Link", spec: b49 },
  { id: "signup-split-quote-image-01", category: "auth", subcategory: "", description: "Signup split quote image: two-column split; uses Field, Input, Button, Link, Avatar", spec: b50 },
  { id: "signup-split-quote-image-02", category: "auth", subcategory: "", description: "Signup split quote image: two-column split; uses Field, Input, Button, Link, Avatar", spec: b51 },
  { id: "social-login-01", category: "auth", subcategory: "social-login", description: "Social login: narrow centered; uses Button, Field, Input, Link", spec: b52 },
  { id: "two-factor-01", category: "auth", subcategory: "two-factor", description: "Two factor: narrow centered; uses Button, Label, InputOTP, Link", spec: b53 },
  { id: "banner-bottom-sticky-01", category: "banners", subcategory: "banner-bottom-sticky", description: "Banner bottom sticky: uses ButtonGroup, Button", spec: b54 },
  { id: "banner-inline-01", category: "banners", subcategory: "banner-inline", description: "Banner inline: uses Button, Image", spec: b55 },
  { id: "banner-top-01", category: "banners", subcategory: "banner-top", description: "Banner top: uses Button", spec: b56 },
  { id: "blog-featured-01", category: "blog", subcategory: "blog-featured", description: "Blog featured: uses Image, Avatar, Button", spec: b57 },
  { id: "blog-grid-01", category: "blog", subcategory: "blog-grid", description: "Blog grid: uses Image", spec: b58 },
  { id: "blog-list-01", category: "blog", subcategory: "blog-list", description: "Blog list: uses Image", spec: b59 },
  { id: "blog-newsletter-01", category: "blog", subcategory: "blog-newsletter", description: "Blog newsletter: uses Image, InputGroup, Input, Button", spec: b60 },
  { id: "blog-post-header-01", category: "blog", subcategory: "blog-post-header", description: "Blog post header: uses Breadcrumbs, Avatar, ButtonGroup, Button, Image", spec: b61 },
  { id: "blog-sidebar-01", category: "blog", subcategory: "blog-sidebar", description: "Blog sidebar: uses Image, Search, NavMenu, List", spec: b62 },
  { id: "before-after-01", category: "comparison", subcategory: "before-after", description: "Before after: uses AspectRatio, Image", spec: b63 },
  { id: "comparison-table-01", category: "comparison", subcategory: "comparison-table", description: "Comparison table: uses DataTable", spec: b64 },
  { id: "vs-layout-01", category: "comparison", subcategory: "vs-layout", description: "Versus layout: Side-by-side comparison of two options with a verdict", spec: b65 },
  { id: "contact-form-simple-01", category: "contact", subcategory: "contact-form-simple", description: "Contact form simple: narrow centered; uses Field, Input, Textarea, Button", spec: b66 },
  { id: "contact-info-01", category: "contact", subcategory: "contact-info", description: "Contact info: uses Button", spec: b67 },
  { id: "contact-offices-01", category: "contact", subcategory: "contact-offices", description: "Contact offices", spec: b68 },
  { id: "contact-split-01", category: "contact", subcategory: "contact-split", description: "Contact split: uses Field, Input, Textarea, Button", spec: b69 },
  { id: "contact-with-map-01", category: "contact", subcategory: "contact-with-map", description: "Contact with map: uses Image, Field, Input, Textarea, Button", spec: b70 },
  { id: "content-numbered-steps-01", category: "content", subcategory: "content-numbered-steps", description: "Content numbered steps: narrow centered; uses Avatar, Button", spec: b71 },
  { id: "content-quote-highlight-01", category: "content", subcategory: "content-quote-highlight", description: "Content quote highlight: narrow centered; uses Avatar, StatCard", spec: b72 },
  { id: "content-section-01", category: "content", subcategory: "content-section", description: "Content section: Long-form text section with image and buttons", spec: b73 },
  { id: "content-split-01", category: "content", subcategory: "content-split", description: "Content split: Two-column text section: heading and intro beside a bulleted list", spec: b74 },
  { id: "content-video-embed-01", category: "content", subcategory: "content-video-embed", description: "Content video embed: uses AspectRatio, Image, List", spec: b75 },
  { id: "content-with-image-01", category: "content", subcategory: "content-with-image", description: "Content with image: uses Image, ButtonGroup, Button", spec: b76 },
  { id: "cta-abstract-images-01", category: "cta", subcategory: "cta-abstract-images", description: "Call-to-action abstract images: Centered call to action flanked by an abstract image collage, with no-contract reassurance copy and dual buttons.", spec: b77 },
  { id: "cta-banner-01", category: "cta", subcategory: "cta-banner", description: "Call-to-action banner: uses Button", spec: b78 },
  { id: "cta-card-horizontal-01", category: "cta", subcategory: "cta-card-horizontal", description: "Call-to-action card horizontal: Horizontal card call to action with trial headline, supporting copy, and side-by-side action buttons.", spec: b79 },
  { id: "cta-card-horizontal-split-01", category: "cta", subcategory: "cta-card-horizontal-split", description: "Call-to-action card horizontal split: Two-tone horizontal card call to action splitting copy and actions across a raised surface.", spec: b80 },
  { id: "cta-card-vertical-01", category: "cta", subcategory: "cta-card-vertical", description: "Call-to-action card vertical: Compact vertical card call to action with centered trial headline and stacked buttons.", spec: b81 },
  { id: "cta-download-01", category: "cta", subcategory: "cta-download", description: "Call-to-action download: two-column split; uses Button, Image", spec: b82 },
  { id: "cta-floating-01", category: "cta", subcategory: "cta-floating", description: "Call-to-action floating: uses Button", spec: b83 },
  { id: "cta-iphone-mockup-01", category: "cta", subcategory: "cta-iphone-mockup", description: "Call-to-action iphone mockup: Split call to action pairing benefit list and buttons with an iPhone app mockup image.", spec: b84 },
  { id: "cta-iphone-mockup-02", category: "cta", subcategory: "cta-iphone-mockup", description: "Call-to-action iphone mockup: Centered call to action with headline, buttons, and an iPhone mockup image below.", spec: b85 },
  { id: "cta-iphone-mockup-03", category: "cta", subcategory: "cta-iphone-mockup", description: "Call-to-action iphone mockup: Minimal trial call to action above a cropped iPhone mockup image.", spec: b86 },
  { id: "cta-iphone-mockup-04", category: "cta", subcategory: "cta-iphone-mockup", description: "Call-to-action iphone mockup: Split call to action with iPhone mockup on the left and benefit list with buttons on the right.", spec: b87 },
  { id: "cta-screen-mockup-01", category: "cta", subcategory: "cta-screen-mockup", description: "Call-to-action screen mockup: Split call to action pairing benefit list and buttons with a desktop app screenshot.", spec: b88 },
  { id: "cta-screen-mockup-02", category: "cta", subcategory: "cta-screen-mockup", description: "Call-to-action screen mockup: Centered call to action with headline and buttons above a desktop app screenshot.", spec: b89 },
  { id: "cta-screen-mockup-03", category: "cta", subcategory: "cta-screen-mockup", description: "Call-to-action screen mockup: Minimal call to action with a full-width desktop app screenshot below the buttons.", spec: b90 },
  { id: "cta-screen-mockup-04", category: "cta", subcategory: "cta-screen-mockup", description: "Call-to-action screen mockup: Split call to action with desktop screenshot on the left and a check-marked feature list with buttons.", spec: b91 },
  { id: "cta-simple-01", category: "cta", subcategory: "cta-simple", description: "Call-to-action simple: narrow centered; uses ButtonGroup, Button", spec: b92 },
  { id: "cta-simple-centered-01", category: "cta", subcategory: "cta-simple-centered", description: "Call-to-action simple centered: Centered headline, supporting line, and button pair on a plain background.", spec: b93 },
  { id: "cta-simple-left-01", category: "cta", subcategory: "cta-simple-left", description: "Call-to-action simple left: Left-aligned call to action with headline, supporting copy, and inline buttons.", spec: b94 },
  { id: "cta-simple-logos-01", category: "cta", subcategory: "cta-simple-logos", description: "Call-to-action simple logos: Centered call to action followed by a separator and a row of customer logos.", spec: b95 },
  { id: "cta-simple-logos-02", category: "cta", subcategory: "cta-simple-logos", description: "Call-to-action simple logos: Call to action beside a grid of customer logos for lightweight social proof.", spec: b96 },
  { id: "cta-split-01", category: "cta", subcategory: "cta-split", description: "Call-to-action split: uses Field, Input, Button", spec: b97 },
  { id: "cta-split-image-01", category: "cta", subcategory: "cta-split-image", description: "Call-to-action split image: Split call to action with startup social-proof headline, benefit list, and a photo panel.", spec: b98 },
  { id: "cta-split-image-02", category: "cta", subcategory: "cta-split-image", description: "Call-to-action split image: Split call to action with photo on the left and trial copy with buttons on the right.", spec: b99 },
  { id: "cta-split-image-03", category: "cta", subcategory: "cta-split-image", description: "Call-to-action split image: Card-framed call to action stacked over a full-width photo.", spec: b100 },
  { id: "cta-split-image-04", category: "cta", subcategory: "cta-split-image", description: "Call-to-action split image: Split call to action pairing a benefit checklist with a photo panel.", spec: b101 },
  { id: "cta-split-image-quote-01", category: "cta", subcategory: "cta-split-image-quote", description: "Call-to-action split image quote: Split call to action with check-marked benefits and a customer quote card over the photo.", spec: b102 },
  { id: "cta-split-image-quote-02", category: "cta", subcategory: "cta-split-image-quote", description: "Call-to-action split image quote: Split call to action with photo and overlaid customer quote on the left, trial copy on the right.", spec: b103 },
  { id: "cta-split-image-quote-03", category: "cta", subcategory: "cta-split-image-quote", description: "Call-to-action split image quote: Split call to action with inline customer quote and avatar under the buttons.", spec: b104 },
  { id: "cta-split-image-quote-04", category: "cta", subcategory: "cta-split-image-quote", description: "Call-to-action split image quote: Stacked call to action with photo, overlaid quote card, and closing buttons.", spec: b105 },
  { id: "cta-with-form-01", category: "cta", subcategory: "cta-with-form", description: "Call-to-action with form: narrow centered; uses Field, Input, Button, AvatarGroup", spec: b106 },
  { id: "activity-feed-01", category: "dashboard", subcategory: "activity-feed", description: "Activity feed: Recent activity list", spec: b107 },
  { id: "chart-panel-01", category: "dashboard", subcategory: "", description: "Chart panel: Chart card with bar chart (6 months revenue) and summary stats row", spec: b108 },
  { id: "chart-section-01", category: "dashboard", subcategory: "chart-section", description: "Chart section: two-column split; uses ChartCard, Chart", spec: b109 },
  { id: "dashboard-header-01", category: "dashboard", subcategory: "dashboard-header", description: "Dashboard header: Dashboard title with date range picker and actions", spec: b110 },
  { id: "data-table-01", category: "dashboard", subcategory: "", description: "Data table: Data table with header bar (title + search + filter), 6 rows, and pagination", spec: b111 },
  { id: "empty-state-panel-01", category: "dashboard", subcategory: "empty-state-panel", description: "Empty state panel: Dashboard panel empty state on a raised surface with icon, explanation, and primary and secondary actions.", spec: b112 },
  { id: "header-01", category: "dashboard", subcategory: "header", description: "Header: App top bar with search, notifications, user menu, breadcrumbs and tabs", spec: b113 },
  { id: "kanban-board-01", category: "dashboard", subcategory: "kanban-board", description: "Kanban board: Task board with to-do, in-progress and done columns of cards", spec: b114 },
  { id: "notification-panel-01", category: "dashboard", subcategory: "notification-panel", description: "Notification panel: uses Button, List", spec: b115 },
  { id: "sidebar-layout-01", category: "dashboard", subcategory: "sidebar-layout", description: "Sidebar layout: uses Sidebar, Search, Button, Avatar, StatCard", spec: b116 },
  { id: "stats-cards-row-01", category: "dashboard", subcategory: "stats-cards-row", description: "Stats cards row: uses StatCard", spec: b117 },
  { id: "stats-row-01", category: "dashboard", subcategory: "", description: "Stats row: 4-column KPI stat cards row (Revenue, Users, Conversion, Avg Order) with trends", spec: b118 },
  { id: "empty-state-01", category: "data-display", subcategory: "", description: "Empty state: Centered empty state with icon, title, message, and action button", spec: b119 },
  { id: "notification-center-01", category: "data-display", subcategory: "", description: "Notification center: Notification list with header, mark-all-read button, and 6 notification items", spec: b120 },
  { id: "profile-01", category: "data-display", subcategory: "", description: "Profile: Profile page with avatar header, 3 stat cards, tabbed content, activity list", spec: b121 },
  { id: "category-grid-01", category: "ecommerce", subcategory: "category-grid", description: "Category grid: Shop-by-category image tiles with product counts", spec: b122 },
  { id: "checkout-form-01", category: "ecommerce", subcategory: "checkout-form", description: "Checkout form: uses Stepper, Field, Input, Select, Checkbox", spec: b123 },
  { id: "order-summary-01", category: "ecommerce", subcategory: "", description: "Order summary: Order summary card with line items, subtotal/shipping/tax/total, promo code, checkout", spec: b124 },
  { id: "product-card-01", category: "ecommerce", subcategory: "product-card", description: "Product card: uses AspectRatio, Image, ToggleGroup, Button", spec: b125 },
  { id: "product-carousel-01", category: "ecommerce", subcategory: "product-carousel", description: "Product carousel: uses ButtonGroup, Button, Image", spec: b126 },
  { id: "product-detail-01", category: "ecommerce", subcategory: "product-detail", description: "Product detail: two-column split; uses AspectRatio, Image, Breadcrumbs, Link, ToggleGroup", spec: b127 },
  { id: "product-grid-01", category: "ecommerce", subcategory: "", description: "Product grid: Product listing with filter chips and 3-column grid of 6 product cards", spec: b128 },
  { id: "shopping-cart-01", category: "ecommerce", subcategory: "shopping-cart", description: "Shopping cart: uses Image, Select, Button, Input", spec: b129 },
  { id: "wishlist-01", category: "ecommerce", subcategory: "wishlist", description: "Wishlist: uses Button, Image, Alert", spec: b130 },
  { id: "404-illustration-01", category: "error-pages", subcategory: "404-illustration", description: "404 illustration: Not-found page with illustration, apologetic headline, and back-home button.", spec: b131 },
  { id: "404-illustration-02", category: "error-pages", subcategory: "404-illustration", description: "404 illustration: Not-found page with illustration plus a search field to recover the visitor.", spec: b132 },
  { id: "404-illustration-03", category: "error-pages", subcategory: "404-illustration", description: "404 illustration: Under-maintenance page with illustration, status headline, and return button.", spec: b133 },
  { id: "404-illustration-04", category: "error-pages", subcategory: "404-illustration", description: "404 illustration: Under-maintenance page with illustration and a search field for finding content meanwhile.", spec: b134 },
  { id: "404-page-01", category: "error-pages", subcategory: "404-page", description: "404 page: uses Image, Search, Button, ButtonGroup, Link", spec: b135 },
  { id: "404-simple-01", category: "error-pages", subcategory: "404-simple", description: "404 simple: Minimal not-found page with large headline, short explanation, and back-home button.", spec: b136 },
  { id: "404-simple-02", category: "error-pages", subcategory: "404-simple", description: "404 simple: Minimal not-found page with back-home button and a support link.", spec: b137 },
  { id: "404-simple-03", category: "error-pages", subcategory: "404-simple", description: "404 simple: Minimal not-found page led by an icon above the headline and button.", spec: b138 },
  { id: "404-simple-04", category: "error-pages", subcategory: "404-simple", description: "404 simple: Not-found page with suggestion cards linking to popular destinations.", spec: b139 },
  { id: "404-split-image-01", category: "error-pages", subcategory: "404-split-image", description: "404 split image: Split not-found page with copy and button beside a photo panel.", spec: b140 },
  { id: "404-split-image-02", category: "error-pages", subcategory: "404-split-image", description: "404 split image: Split not-found page pairing a search field with a photo panel.", spec: b141 },
  { id: "404-split-image-03", category: "error-pages", subcategory: "404-split-image", description: "404 split image: Not-found page with copy over a full-width photo.", spec: b142 },
  { id: "404-split-image-04", category: "error-pages", subcategory: "404-split-image", description: "404 split image: Split not-found page with search, quick links, and a photo panel.", spec: b143 },
  { id: "500-page-01", category: "error-pages", subcategory: "500-page", description: "500 page: uses Image, ButtonGroup, Button, Alert", spec: b144 },
  { id: "coming-soon-01", category: "error-pages", subcategory: "coming-soon", description: "Coming soon: uses Progress, Input, Button", spec: b145 },
  { id: "maintenance-page-01", category: "error-pages", subcategory: "maintenance-page", description: "Maintenance page: uses Image, Progress, Input, Button", spec: b146 },
  { id: "event-countdown-01", category: "event-schedule", subcategory: "event-countdown", description: "Event countdown: Event hero with date, venue, countdown and register buttons", spec: b147 },
  { id: "schedule-tabs-01", category: "event-schedule", subcategory: "schedule-tabs", description: "Schedule tabs: Event agenda tabbed by day with session lists", spec: b148 },
  { id: "speaker-grid-01", category: "event-schedule", subcategory: "speaker-grid", description: "Speaker grid: Grid of speaker cards with photo, name, role and talk tag", spec: b149 },
  { id: "faq-accordion-01", category: "faq", subcategory: "faq-accordion", description: "FAQ accordion: uses Accordion", spec: b150 },
  { id: "faq-grid-01", category: "faq", subcategory: "faq-grid", description: "FAQ grid", spec: b151 },
  { id: "faq-simple-01", category: "faq", subcategory: "faq-simple", description: "FAQ simple", spec: b152 },
  { id: "faq-with-sidebar-01", category: "faq", subcategory: "faq-with-sidebar", description: "FAQ with sidebar: uses NavMenu, Accordion, Button", spec: b153 },
  { id: "feature-alternating-01", category: "features", subcategory: "feature-alternating", description: "Feature alternating: uses Image, Button", spec: b154 },
  { id: "feature-bento-01", category: "features", subcategory: "feature-bento", description: "Feature bento: uses Image", spec: b155 },
  { id: "feature-centered-01", category: "features", subcategory: "feature-centered", description: "Feature centered: narrow centered; uses Image", spec: b156 },
  { id: "feature-comparison-01", category: "features", subcategory: "feature-comparison", description: "Feature comparison: uses List", spec: b157 },
  { id: "feature-grid-01", category: "features", subcategory: "feature-grid", description: "Feature grid", spec: b158 },
  { id: "feature-icon-grid-01", category: "features", subcategory: "feature-icon-grid", description: "Feature icon grid", spec: b159 },
  { id: "feature-list-01", category: "features", subcategory: "feature-list", description: "Feature list: narrow centered", spec: b160 },
  { id: "feature-tabs-01", category: "features", subcategory: "feature-tabs", description: "Feature tabs: uses Tabs, List, Image", spec: b161 },
  { id: "feature-with-code-01", category: "features", subcategory: "feature-with-code", description: "Feature with code: Developer feature section with a code sample", spec: b162 },
  { id: "footer-columns-01", category: "footer", subcategory: "footer-columns", description: "Footer columns: uses NavMenu, ButtonGroup, Button", spec: b163 },
  { id: "footer-mega-01", category: "footer", subcategory: "footer-mega", description: "Footer mega: uses NavMenu, Input, Button, ButtonGroup", spec: b164 },
  { id: "footer-minimal-01", category: "footer", subcategory: "footer-minimal", description: "Footer minimal: uses NavMenu", spec: b165 },
  { id: "footer-simple-01", category: "footer", subcategory: "footer-simple", description: "Footer simple: uses NavMenu, ButtonGroup, Button", spec: b166 },
  { id: "footer-with-cta-01", category: "footer", subcategory: "footer-with-cta", description: "Footer with call-to-action: uses ButtonGroup, Button, NavMenu", spec: b167 },
  { id: "checkout-01", category: "forms", subcategory: "checkout", description: "Checkout: uses Field, Select, Button", spec: b168 },
  { id: "contact-01", category: "forms", subcategory: "contact", description: "Contact: uses Field, Select, Label, Textarea, Button", spec: b169 },
  { id: "file-upload-01", category: "forms", subcategory: "file-upload", description: "File upload: uses Button, Progress", spec: b170 },
  { id: "form-inline-01", category: "forms", subcategory: "form-inline", description: "Form inline: uses Field, Search, Select, Button", spec: b171 },
  { id: "form-multi-step-01", category: "forms", subcategory: "form-multi-step", description: "Form multi step: uses Stepper, Field, Input, Checkbox, Button", spec: b172 },
  { id: "form-stacked-01", category: "forms", subcategory: "form-stacked", description: "Form stacked: uses Field, Input, Select, Textarea, Button", spec: b173 },
  { id: "form-with-sidebar-01", category: "forms", subcategory: "form-with-sidebar", description: "Form with sidebar: uses Field, Input, Textarea, Select, RadioGroup", spec: b174 },
  { id: "login-01", category: "forms", subcategory: "login", description: "Login: uses Field, Checkbox, Button", spec: b175 },
  { id: "search-bar-01", category: "forms", subcategory: "search-bar", description: "Search bar: uses Search, Button, List", spec: b176 },
  { id: "settings-01", category: "forms", subcategory: "settings", description: "Settings: uses Field, Label, Textarea, Switch, Button", spec: b177 },
  { id: "settings-form-01", category: "forms", subcategory: "settings-form", description: "Settings form: uses Switch, Select, ToggleGroup, Button", spec: b178 },
  { id: "signup-01", category: "forms", subcategory: "signup", description: "Signup: uses Field, Checkbox, Button, Link", spec: b179 },
  { id: "hero-centered-01", category: "hero", subcategory: "hero-centered", description: "Hero centered: narrow centered; uses Button, AvatarGroup, Avatar", spec: b180 },
  { id: "hero-fullscreen-01", category: "hero", subcategory: "hero-fullscreen", description: "Hero fullscreen: uses Avatar, Button", spec: b181 },
  { id: "hero-minimal-01", category: "hero", subcategory: "hero-minimal", description: "Hero minimal: narrow centered; uses Button", spec: b182 },
  { id: "hero-split-01", category: "hero", subcategory: "hero-split", description: "Hero split: two-column split; uses Button, Image", spec: b183 },
  { id: "hero-video-background-01", category: "hero", subcategory: "hero-video-background", description: "Hero video background: uses CustomHTML, Button", spec: b184 },
  { id: "hero-with-app-screenshot-01", category: "hero", subcategory: "hero-with-app-screenshot", description: "Hero with app screenshot: uses Button, Image", spec: b185 },
  { id: "hero-with-form-01", category: "hero", subcategory: "hero-with-form", description: "Hero with form: two-column split; uses List, Field, Input, Select, Button", spec: b186 },
  { id: "hero-with-stats-01", category: "hero", subcategory: "hero-with-stats", description: "Hero with stats: uses Button, StatCard", spec: b187 },
  { id: "process-alternating-01", category: "how-it-works", subcategory: "process-alternating", description: "Process alternating: Numbered process steps with alternating image and text", spec: b188 },
  { id: "steps-horizontal-01", category: "how-it-works", subcategory: "steps-horizontal", description: "Steps horizontal: uses Stepper, Avatar", spec: b189 },
  { id: "steps-vertical-01", category: "how-it-works", subcategory: "steps-vertical", description: "Steps vertical: uses Avatar, Button", spec: b190 },
  { id: "api-reference-01", category: "integrations", subcategory: "api-reference", description: "API reference: Endpoint list with HTTP method badges, paths and descriptions for developer docs", spec: b191 },
  { id: "integration-grid-01", category: "integrations", subcategory: "integration-grid", description: "Integration grid: uses Avatar, Button", spec: b192 },
  { id: "integration-showcase-01", category: "integrations", subcategory: "integration-showcase", description: "Integration showcase: uses Image, List, ButtonGroup, Button", spec: b193 },
  { id: "features-grid-01", category: "landing", subcategory: "", description: "Features grid: 6-item feature grid with icons, titles, and descriptions in 3 columns", spec: b194 },
  { id: "footer-01", category: "landing", subcategory: "", description: "Footer: 4-column link footer (Product/Company/Resources/Legal) with copyright", spec: b195 },
  { id: "hero-01", category: "landing", subcategory: "", description: "Hero: Centered hero with heading, subheading, CTA button, and decorative image", spec: b196 },
  { id: "pricing-01", category: "landing", subcategory: "", description: "Pricing: 3-tier pricing cards (Free/Pro/Enterprise) with features and CTA buttons", spec: b197 },
  { id: "testimonials-01", category: "landing", subcategory: "", description: "Testimonials: 3 testimonial cards with quotes, avatars, names, and roles", spec: b198 },
  { id: "logo-cloud-scrolling-01", category: "logo-bar", subcategory: "logo-cloud-scrolling", description: "Logo cloud scrolling: uses ScrollArea", spec: b199 },
  { id: "logo-cloud-simple-01", category: "logo-bar", subcategory: "logo-cloud-simple", description: "Logo cloud simple", spec: b200 },
  { id: "logo-cloud-with-heading-01", category: "logo-bar", subcategory: "logo-cloud-with-heading", description: "Logo cloud with heading: narrow centered", spec: b201 },
  { id: "gallery-carousel-01", category: "media", subcategory: "gallery-carousel", description: "Gallery carousel: uses ButtonGroup, Button, Image", spec: b202 },
  { id: "gallery-grid-01", category: "media", subcategory: "gallery-grid", description: "Gallery grid: uses Image", spec: b203 },
  { id: "media-with-text-01", category: "media", subcategory: "media-with-text", description: "Media with text: two-column split; uses AspectRatio, Image, ButtonGroup, Button", spec: b204 },
  { id: "video-section-01", category: "media", subcategory: "video-section", description: "Video section: uses AspectRatio, Image, Button", spec: b205 },
  { id: "back-to-top-01", category: "misc", subcategory: "back-to-top", description: "Back to top: uses Button", spec: b206 },
  { id: "divider-01", category: "misc", subcategory: "divider", description: "Divider", spec: b207 },
  { id: "language-switcher-01", category: "misc", subcategory: "language-switcher", description: "Language switcher: uses Select", spec: b208 },
  { id: "scroll-indicator-01", category: "misc", subcategory: "scroll-indicator", description: "Scroll indicator: uses Progress", spec: b209 },
  { id: "skip-link-01", category: "misc", subcategory: "skip-link", description: "Skip link: uses Button", spec: b210 },
  { id: "social-links-01", category: "misc", subcategory: "social-links", description: "Social links: uses ButtonGroup, Button", spec: b211 },
  { id: "table-of-contents-01", category: "misc", subcategory: "table-of-contents", description: "Table of contents: In-page navigation list for long docs or articles", spec: b212 },
  { id: "theme-toggle-01", category: "misc", subcategory: "theme-toggle", description: "Theme toggle: narrow centered; uses Toggle", spec: b213 },
  { id: "app-shell-01", category: "mobile", subcategory: "", description: "App shell: Mobile layout with top navbar, content area, and bottom navigation (5 tabs)", spec: b214 },
  { id: "command-palette-01", category: "modals-overlays", subcategory: "command-palette", description: "Command palette: narrow centered; uses Input, List", spec: b215 },
  { id: "cookie-consent-01", category: "modals-overlays", subcategory: "cookie-consent", description: "Cookie consent: uses Button", spec: b216 },
  { id: "drawer-01", category: "modals-overlays", subcategory: "drawer", description: "Drawer: uses Drawer, Field, Input, Select, Checkbox", spec: b217 },
  { id: "lightbox-01", category: "modals-overlays", subcategory: "lightbox", description: "Lightbox: uses AspectRatio, Image, Button", spec: b218 },
  { id: "modal-confirm-01", category: "modals-overlays", subcategory: "modal-confirm", description: "Modal confirm: uses List, Button", spec: b219 },
  { id: "modal-dialog-01", category: "modals-overlays", subcategory: "modal-dialog", description: "Modal dialog: uses Avatar, Button, Field, Input, Textarea", spec: b220 },
  { id: "toast-notification-01", category: "modals-overlays", subcategory: "toast-notification", description: "Toast notification: uses Alert", spec: b221 },
  { id: "bottom-nav-01", category: "navigation", subcategory: "bottom-nav", description: "Bottom nav: uses BottomNav", spec: b222 },
  { id: "breadcrumbs-01", category: "navigation", subcategory: "breadcrumbs", description: "Breadcrumbs: uses Breadcrumbs", spec: b223 },
  { id: "navbar-mega-menu-01", category: "navigation", subcategory: "navbar-mega-menu", description: "Navbar mega menu: uses Link, Button", spec: b224 },
  { id: "navbar-mobile-drawer-01", category: "navigation", subcategory: "navbar-mobile-drawer", description: "Navbar mobile drawer: uses Button, Sheet, NavMenu", spec: b225 },
  { id: "navbar-simple-01", category: "navigation", subcategory: "navbar-simple", description: "Navbar simple: uses Link, Button", spec: b226 },
  { id: "navbar-with-auth-01", category: "navigation", subcategory: "navbar-with-auth", description: "Navbar with auth: uses Link, Button", spec: b227 },
  { id: "navbar-with-search-01", category: "navigation", subcategory: "navbar-with-search", description: "Navbar with search: uses Link, Search, Button, Avatar", spec: b228 },
  { id: "pagination-01", category: "navigation", subcategory: "pagination", description: "Pagination: uses Select, Pagination", spec: b229 },
  { id: "sidebar-nav-01", category: "navigation", subcategory: "sidebar-nav", description: "Sidebar nav: uses Sidebar", spec: b230 },
  { id: "tab-nav-01", category: "navigation", subcategory: "tab-nav", description: "Tab nav: uses Button, Tabs, Field, Input, Select", spec: b231 },
  { id: "topbar-announcement-01", category: "navigation", subcategory: "topbar-announcement", description: "Topbar announcement: uses Link", spec: b232 },
  { id: "newsletter-card-01", category: "newsletter", subcategory: "newsletter-card", description: "Newsletter card: uses Field, Input, Button", spec: b233 },
  { id: "newsletter-footer-01", category: "newsletter", subcategory: "newsletter-footer", description: "Newsletter footer: uses Button, InputGroup, Input", spec: b234 },
  { id: "newsletter-inline-01", category: "newsletter", subcategory: "newsletter-inline", description: "Newsletter inline: uses InputGroup, Input, Button", spec: b235 },
  { id: "newsletter-popup-01", category: "newsletter", subcategory: "newsletter-popup", description: "Newsletter popup: narrow centered; uses Input, Button", spec: b236 },
  { id: "portfolio-carousel-01", category: "portfolio", subcategory: "portfolio-carousel", description: "Portfolio carousel: uses ButtonGroup, Button, Image", spec: b237 },
  { id: "portfolio-case-study-01", category: "portfolio", subcategory: "portfolio-case-study", description: "Portfolio case study: uses Breadcrumbs, Image, StatCard, Prose, List", spec: b238 },
  { id: "portfolio-grid-01", category: "portfolio", subcategory: "portfolio-grid", description: "Portfolio grid: uses ToggleGroup, Image", spec: b239 },
  { id: "pricing-calculator-01", category: "pricing", subcategory: "pricing-calculator", description: "Pricing calculator: narrow centered; uses Slider, Button", spec: b240 },
  { id: "pricing-comparison-table-01", category: "pricing", subcategory: "pricing-comparison-table", description: "Pricing comparison table: uses DataTable, Button", spec: b241 },
  { id: "pricing-faq-01", category: "pricing", subcategory: "pricing-faq", description: "Pricing FAQ: narrow centered; uses Accordion, ButtonGroup, Button", spec: b242 },
  { id: "pricing-single-01", category: "pricing", subcategory: "pricing-single", description: "Pricing single: narrow centered; uses Button", spec: b243 },
  { id: "pricing-tiers-01", category: "pricing", subcategory: "pricing-tiers", description: "Pricing tiers: uses Button, List", spec: b244 },
  { id: "pricing-toggle-01", category: "pricing", subcategory: "pricing-toggle", description: "Pricing toggle: uses ToggleGroup, Button, List", spec: b245 },
  { id: "case-study-card-01", category: "social-proof", subcategory: "case-study-card", description: "Case study card: uses StatCard, Avatar", spec: b246 },
  { id: "press-mentions-01", category: "social-proof", subcategory: "press-mentions", description: "Press mentions: As-featured-in row of publication names", spec: b247 },
  { id: "review-stars-01", category: "social-proof", subcategory: "review-stars", description: "Review stars: Rating summary with average score, star distribution bars and reviews", spec: b248 },
  { id: "social-proof-bar-01", category: "social-proof", subcategory: "social-proof-bar", description: "Social proof bar: Strip of trust numbers: customer count, star rating, review sites", spec: b249 },
  { id: "testimonial-carousel-01", category: "social-proof", subcategory: "testimonial-carousel", description: "Testimonial carousel: uses Avatar, ButtonGroup, Button", spec: b250 },
  { id: "testimonial-grid-01", category: "social-proof", subcategory: "testimonial-grid", description: "Testimonial grid: uses Avatar", spec: b251 },
  { id: "testimonial-single-01", category: "social-proof", subcategory: "testimonial-single", description: "Testimonial single: narrow centered; uses Avatar", spec: b252 },
  { id: "testimonial-wall-01", category: "social-proof", subcategory: "testimonial-wall", description: "Testimonial wall: uses Avatar", spec: b253 },
  { id: "stats-counter-01", category: "stats", subcategory: "stats-counter", description: "Stats counter: Row of large headline numbers with labels", spec: b254 },
  { id: "stats-grid-01", category: "stats", subcategory: "stats-grid", description: "Stats grid: uses StatCard", spec: b255 },
  { id: "stats-strip-01", category: "stats", subcategory: "stats-strip", description: "Stats strip: Slim horizontal strip of headline metrics divided by separators.", spec: b256 },
  { id: "stats-with-description-01", category: "stats", subcategory: "stats-with-description", description: "Stats with description: uses Button", spec: b257 },
  { id: "team-carousel-01", category: "team", subcategory: "team-carousel", description: "Team carousel: uses Avatar, ButtonGroup, Button", spec: b258 },
  { id: "team-featured-01", category: "team", subcategory: "team-featured", description: "Team featured: uses Image, Prose, Button", spec: b259 },
  { id: "team-grid-01", category: "team", subcategory: "team-grid", description: "Team grid: uses Avatar", spec: b260 },
  { id: "team-list-01", category: "team", subcategory: "team-list", description: "Team list: uses Avatar", spec: b261 },
  { id: "changelog-01", category: "timeline", subcategory: "changelog", description: "Changelog: Dated release notes with version badges", spec: b262 },
  { id: "roadmap-01", category: "timeline", subcategory: "roadmap", description: "Roadmap: uses Stepper, List, Progress", spec: b263 },
  { id: "timeline-horizontal-01", category: "timeline", subcategory: "timeline-horizontal", description: "Timeline horizontal: uses ScrollArea", spec: b264 },
  { id: "timeline-vertical-01", category: "timeline", subcategory: "timeline-vertical", description: "Timeline vertical: uses List", spec: b265 },
];
