#!/usr/bin/env bash
# Strip dev-only artifacts from the Pages deploy root.
# Everything here is .gitignored or generated by local test/audit tooling.
set -euo pipefail
cd "$(dirname "$0")/.."

# Root-level screenshots and snapshots (see .gitignore)
rm -f bridge-test.png chat-input-improved.png react-chat-*.png state-*.png \
      toggle-*.png temp-slider-*.png themes-*.png codedb.snapshot \
      index.playground-chat.js.map

# Audit harness output (screenshots + reports). Harness source at
# tests/component-audit/ is kept (small, documents the rig).
rm -rf test-results
